# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(829, 288)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 288))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 291))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/notesmain.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet(_fromUtf8("QToolButton \n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(320, 240))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.playingLabel = QtGui.QLabel(self.centralwidget)
        self.playingLabel.setObjectName(_fromUtf8("playingLabel"))
        self.verticalLayout_3.addWidget(self.playingLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.songLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songLabel.sizePolicy().hasHeightForWidth())
        self.songLabel.setSizePolicy(sizePolicy)
        self.songLabel.setMaximumSize(QtCore.QSize(320, 16777215))
        self.songLabel.setWordWrap(False)
        self.songLabel.setObjectName(_fromUtf8("songLabel"))
        self.verticalLayout_3.addWidget(self.songLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.verticalLayout_3.addWidget(self.timeLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.previousButton = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setIconSize(QtCore.QSize(48, 48))
        self.previousButton.setObjectName(_fromUtf8("previousButton"))
        self.horizontalLayout_2.addWidget(self.previousButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.backButton = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/seekback.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon2)
        self.backButton.setIconSize(QtCore.QSize(48, 48))
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.horizontalLayout_2.addWidget(self.backButton)
        self.playButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playButton.setIcon(icon3)
        self.playButton.setIconSize(QtCore.QSize(48, 48))
        self.playButton.setCheckable(True)
        self.playButton.setChecked(False)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_2.addWidget(self.playButton)
        self.stopButton = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon4)
        self.stopButton.setIconSize(QtCore.QSize(48, 48))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.forwardButton = QtGui.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/seekforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon5)
        self.forwardButton.setIconSize(QtCore.QSize(48, 48))
        self.forwardButton.setObjectName(_fromUtf8("forwardButton"))
        self.horizontalLayout_2.addWidget(self.forwardButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.nextButton = QtGui.QToolButton(self.centralwidget)
        self.nextButton.setStyleSheet(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon6)
        self.nextButton.setIconSize(QtCore.QSize(48, 48))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_2.addWidget(self.nextButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.shuffleBox = QtGui.QCheckBox(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/shuffle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/shuffle.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.shuffleBox.setIcon(icon7)
        self.shuffleBox.setChecked(True)
        self.shuffleBox.setObjectName(_fromUtf8("shuffleBox"))
        self.horizontalLayout_3.addWidget(self.shuffleBox, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.muteButton = QtGui.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/volumemute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteButton.setIcon(icon8)
        self.muteButton.setObjectName(_fromUtf8("muteButton"))
        self.horizontalLayout_3.addWidget(self.muteButton)
        self.volumeSlider = QtGui.QSlider(self.centralwidget)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setSingleStep(10)
        self.volumeSlider.setSliderPosition(100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.volumeSlider.setTickInterval(10)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.horizontalLayout_3.addWidget(self.volumeSlider)
        self.maxButton = QtGui.QToolButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/volumemax.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxButton.setIcon(icon9)
        self.maxButton.setObjectName(_fromUtf8("maxButton"))
        self.horizontalLayout_3.addWidget(self.maxButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.repeatBox = QtGui.QCheckBox(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.repeatBox.setIcon(icon10)
        self.repeatBox.setChecked(True)
        self.repeatBox.setObjectName(_fromUtf8("repeatBox"))
        self.horizontalLayout_3.addWidget(self.repeatBox, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.playlistWidget = QtGui.QListWidget(self.centralwidget)
        self.playlistWidget.setObjectName(_fromUtf8("playlistWidget"))
        self.horizontalLayout.addWidget(self.playlistWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pyqt-music", None))
        self.playingLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Playing</span></p></body></html>", None))
        self.songLabel.setText(_translate("MainWindow", "Song", None))
        self.timeLabel.setText(_translate("MainWindow", "0/0", None))
        self.previousButton.setText(_translate("MainWindow", "Previous", None))
        self.backButton.setText(_translate("MainWindow", "...", None))
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.forwardButton.setText(_translate("MainWindow", "...", None))
        self.nextButton.setText(_translate("MainWindow", "Next", None))
        self.shuffleBox.setText(_translate("MainWindow", "Shuffle", None))
        self.muteButton.setText(_translate("MainWindow", "...", None))
        self.maxButton.setText(_translate("MainWindow", "...", None))
        self.repeatBox.setText(_translate("MainWindow", "Repeat", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

import res_rc
